-- Supports the mobile app's "More Info" screen:
--   * more icons a row can use (wifi, camera, trophy, presentation, demo,
--     address-book) — the mobile app's fixed icon set, kept in sync with
--     EVENT_INFO_SECTION_ICONS in the admin app
--   * a row can open an existing screen instead of a text page
--     (link_target; 'speakers' for now)
--   * an image of the venue area shown in the Location block, which links
--     to the address in Maps (events.location_image_url)
--   * https-only guards on the admin-entered link columns

-- 1. Icons. The original CHECK was inline on the column, so Postgres named
--    it event_info_sections_icon_check.
alter table public.event_info_sections
  drop constraint if exists event_info_sections_icon_check;

alter table public.event_info_sections
  add constraint event_info_sections_icon_check check (icon in (
    'tree-pine', 'info', 'plane', 'users', 'heart',
    'building', 'clipboard-list', 'map', 'map-pin',
    'wifi', 'camera', 'trophy', 'presentation', 'demo', 'address-book'
  ));

-- 2. A row that opens an existing screen. Null = a normal page of text.
alter table public.event_info_sections
  add column if not exists link_target text
    check (link_target is null or link_target in ('speakers'));

-- 3. Venue area image (uploaded to the event-media bucket, like the logo
--    and banners).
alter table public.events
  add column if not exists location_image_url text;

-- 4. https-only guards, NOT VALID so they apply to new and edited rows and
--    can't fail on anything written before. Validate later with:
--      alter table public.events validate constraint events_links_https;
--      alter table public.sponsors validate constraint sponsors_website_https;
--    Only link columns are guarded; image URLs are generated by Storage.
alter table public.events
  drop constraint if exists events_links_https;

alter table public.events
  add constraint events_links_https check (
    (banner_1_link_url is null or (banner_1_link_url ~ '^https://[^[:space:]]+$' and char_length(banner_1_link_url) <= 2048)) and
    (banner_2_link_url is null or (banner_2_link_url ~ '^https://[^[:space:]]+$' and char_length(banner_2_link_url) <= 2048))
  ) not valid;

alter table public.sponsors
  drop constraint if exists sponsors_website_https;

alter table public.sponsors
  add constraint sponsors_website_https check (
    website_url is null or (website_url ~ '^https://[^[:space:]]+$' and char_length(website_url) <= 2048)
  ) not valid;
